name: PSI

on: push

env:
    REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: v1.x
      
      - run: deno run -A psi.ts https://deco-sites-${REPO_NAME}.deno.dev/ -c 5