name: PSI

on: push

env:
    REPO_NAME: ${{ github.event.repository.name }}
    GIT_HASH: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: v1.x
      
      - run: deno run -A psi.ts https://deco-sites-zorba.deno.dev/ -c 5 --hash ${GIT_HASH}
      - run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git pull
            git add .
            git commit -m "generated"
            git push